export enum PostActionTypes {
  SET_POSTS = 'POST/SET_POSTS',
  SET_POST_LOADING = 'POST/SET_POST_LOADING',
  SET_POST_ERROR = 'POST/SET_POSTS_ERROR',

  GET_POSTS = 'POST/GET_POSTS',
  GET_POST = 'POST/GET_POST',
  ADD_POST = 'POST/ADD_POST',
  UPDATE_POST = 'POST/UPDATE_POST',
  DELETE_POST = 'POST/DELETE_POST'
}
